[tool.uv]
# This root is a workspace, not an installable package
package = false

[tool.uv.workspace]
# Add more packages here later, e.g. django-lenskit-core, etc.
members = [
    "packages/django_lenskit_admin",
    "packages/django_lenskit_audit",
    "packages/django_lenskit_fixtures",
    "packages/django_lenskit_ai_query",
]

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [
    ".venv",
    ".uv",
    "build",
    "dist",
]

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true
ignore_missing_imports = true
strict = true

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = [
    "packages",
]
DJANGO_SETTINGS_MODULE = "django_lenskit_audit.tests.settings"

[dependency-groups]
dev = [
    "python-dotenv>=1.2.1",
    "ruff>=0.14.8",
]
